# Generated by Django 4.1.3 on 2022-11-26 18:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_placeimage_options_placeimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(help_text='Полное описание', max_length=10000),
        ),
    ]
